#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

SCALA_VERSION='2.9.2'
SCALA_DIST_DIR='http://www.scala-lang.org/downloads/distrib/files'
PLAY_VERSION='2.0.4'
PLAY_DIST_DIR='http://download.playframework.org/releases'

pushd ${OPENSHIFT_DATA_DIR} > /dev/null
if [ ! -d scala-${SCALA_VERSION} ]; then
  wget ${SCALA_DIST_DIR}/scala-${SCALA_VERSION}.tgz
  tar xzf scala-${SCALA_VERSION}.tgz
fi
export PATH=$PATH:${OPENSHIFT_DATA_DIR}scala-${SCALA_VERSION}/bin

if [ ! -d play-${PLAY_VERSION} ]; then
  wget ${PLAY_DIST_DIR}/play-${PLAY_VERSION}.zip
  unzip play-${PLAY_VERSION}.zip > /dev/null
fi
export PATH=$PATH:${OPENSHIFT_DATA_DIR}play-2.0.4

popd > /dev/null