#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_LOG_DIR/server.log 2>&1 &

source `dirname $0`/vars

export PATH=$PATH:${OPENSHIFT_DATA_DIR}scala-${SCALA_VERSION}/bin

export PATH=$PATH:${OPENSHIFT_DATA_DIR}play-2.0.4

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
play "start 8080" > ${OPENSHIFT_LOG_DIR}/server.log 2>&1 &
popd > /dev/null
