#!/bin/bash
# The logic to stop your application should be put in this script.

source `dirname $0`/vars

export PATH=$PATH:${OPENSHIFT_DATA_DIR}scala-${SCALA_VERSION}/bin

export PATH=$PATH:${OPENSHIFT_DATA_DIR}play-2.0.4

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
play stop >> ${OPENSHIFT_LOG_DIR}/server.log 2>&1 &
popd > /dev/null
